pipeline {
    agent any
    stages {
        stage("Checkout Codebase") {
            steps {
                cleanWs()
                checkout scm: [$class: 'GitSCM', branches: [[name: '*/main']], userRemoteConfigs: [[credentialsId: 'Github', url: 'https://github.com/wedla/prova-pags']]]
            }
        }
        stage("Build API status code") {
            steps {
                sh "ls"
                sh "docker build -t my_image ."
                sh "docker run my_image"
            }
        }
        stage("Build API status code") {
            steps {
                sh "ls"
                sh "docker build -t my_image ."
                sh "docker run my_image"
            }
        }
    }
}